name: restormer_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=2.16
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - certifi=2024.8.30
  - cudatoolkit=11.1.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gnutls=3.6.13
  - intel-openmp=2025.0.0
  - jpeg=9b
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.4.4
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=15.1.0
  - libiconv=1.18
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnsl=2.0.1
  - libpng=1.6.43
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libtiff=4.2.0
  - libuv=1.51.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.17.0
  - libzlib=1.2.13
  - lz4-c=1.9.3
  - mkl=2020.2
  - ncurses=6.5
  - nettle=3.6
  - numpy=1.21.6
  - openh264=2.1.1
  - openssl=3.5.2
  - pillow=9.3.0
  - pip=22.3.1
  - pthread-stubs=0.3
  - python=3.7.12
  - python_abi=3.7
  - pytorch=1.8.1
  - readline=8.3
  - setuptools=65.6.3
  - sqlite=3.50.2
  - tk=8.6.15
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - typing_extensions=4.7.1
  - wheel=0.38.4
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
      - absl-py==2.1.0
      - albumentations==1.1.0
      - cachetools==5.5.2
      - charset-normalizer==3.4.3
      - click==8.1.8
      - docker-pycreds==0.4.0
      - efficientnet-pytorch==0.6.3
      - einops==0.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - grpcio==1.62.3
      - idna==3.10
      - imageio==2.31.2
      - importlib-metadata==6.7.0
      - joblib==1.3.2
      - lmdb==1.7.3
      - lpips==0.1.4
      - markdown==3.4.4
      - markupsafe==2.1.5
      - munch==4.0.0
      - networkx==2.6.3
      - ninja==1.11.1.4
      - noise==1.2.2
      - oauthlib==3.2.2
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opensimplex==0.4.2
      - packaging==24.0
      - pandas==1.3.5
      - platformdirs==4.0.0
      - pretrainedmodels==0.7.4
      - protobuf==3.20.3
      - psutil==7.0.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.3.0
      - pyyaml==6.0.1
      - qudida==0.0.4
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9.1
      - scikit-image==0.19.3
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - segmentation-models-pytorch==0.2.1
      - sentry-sdk==2.35.1
      - setproctitle==1.3.3
      - six==1.17.0
      - smmap==5.0.2
      - split-folders==0.5.1
      - tensorboard==2.11.2
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - threadpoolctl==3.1.0
      - tifffile==2021.11.2
      - timm==0.4.12
      - tqdm==4.67.1
      - urllib3==2.0.7
      - wandb==0.18.7
      - werkzeug==2.2.3
      - zipp==3.15.0
